### ISSUE TITLE
Tags in YAML?

### ISSUE THREAD

**Issue by luddeluddis** [inkdropapp/inkdrop-export-as-markdown#3]
Hi! Thanks for great software. I've noticed that you´ve done some updates of the export functions recently. Do you plan to include tags in YAML when exporting notes as markdown together with time-information? That's a function I very much would like to see as a way to preserve future compatibility!

**Comment by craftzdog** [comment]
Hi, thank you for the suggestion.
I understand the exportability is important for your workflow.
It would be nice to support including tags and dates in exported YAML frontmatter.
The problem is that people have various preferences for the exported format.
Some people may not want to include tags. Some people may want to include tags in `keyword:` instead of `tags:` field. That depends on their preferences.
So, I would rather add more flexibility that allows you to customize the export format than just adding the tag support. But that would take some time to accomplish it. I think integrating with [micromark](https://github.com/micromark/micromark) to process markdown would be great.
Currently, I'm working on [the current roadmap here](https://blog.inkdrop.info/the-roadmap-of-inkdrop-vol-5-251c3997bb74).
Let me revisit this after finishing it!

**Comment by luddeluddis** [comment]
Thanks for your answer! A future option to customize the export format, would of course, be very much appreciated. I understand that it will take some work/time, but great to hear that it´s something you will consider in the future. Take care!

**Comment by craftzdog** [comment]
[live-export](https://github.com/inkdropapp/inkdrop-live-export) supports exporting notes while tweaking their YAML frontmatters programmatically. Check it out.
